-- CREATE DATABASE 
CREATE DATABASE BD_DEMO;
--END
-- USE DATA  BANK 
USE BD_DEMO;
-- CREATE TABLE CLIENTES
BEGIN
	CREATE TABLE TB_CLIENTES (
		IdClientes INT NOT NULL IDENTITY(1,1)
		
		,Nome VARCHAR(50) NOT NULL
		,SobreNome VARCHAR(150) NOT NULL

		,CPF VARCHAR(50) NOT NULL

		-- CONTATOS
		,CEP VARCHAR(15)
		,Endereco VARCHAR(250)
		,Num INT
		,Complemento VARCHAR(25)
		,Bairro VARCHAR(250)

		,Telefone1 VARCHAR(15)
		,Telefone2 VARCHAR(15)
		,Email VARCHAR(250)

		,DataCricao DATETIME NOT NULL DEFAULT(CONVERT(datetime, SYSDATETIMEOFFSET() AT TIME ZONE 'E. South America Standard Time')) 
		,DataAlteracao DATETIME NOT NULL DEFAULT(CONVERT(datetime, SYSDATETIMEOFFSET() AT TIME ZONE 'E. South America Standard Time'))

		-- ,Excluir BIT DEFAULT(0) NOT NULL
);
END
--END